### ISSUE TITLE
Can we use `./configure` in `build.sh`?

### ISSUE THREAD

**Issue by drozdziak1** [solana-labs/rust#12]
Hey, I was thinking about building this toolchain using [nix](nixos.org). In order to be able to do that I need flags which need to be passed over to `./configure` so that the Nix build can work its magic by passing the right stuff to the resulting `Makefile`.

A reproducible build of the Solana ecosystem sounds like a great way to make life easier for validator operators and virtually anyone hosting Solana infrastructure.

That said, I believe my biggest bottleneck at the moment is lack of knowledge of the rustc sources necessary to understand Solana-specific changes better.

**Comment by dmakarov** [comment]
I'm not sure which Makefile you mention. The compiler and libraries build is controlled by cargo entirely without using configure script or Makefile.  If the upstream rust-lang/rust builds on your system, Solana fork should build as well.

**Comment by drozdziak1** [comment]
`./configure` produces a top-level Makefile, that's the one I mean

**Comment by dmakarov** [comment]
rust build does not use Makefile anymore. All build commands are executed and controlled by cargo.

**Comment by drozdziak1** [comment]
Oh, you're right, they seem to want to phase it out. Well, dealing with the Makefile is on me then.

Makefile aside, would you be open about a PR that would produce a set of options identical to present `config.toml` via `./configure` inside `build.sh`?

I could see this fork benefiting from this by being able to discover and add options of interest more easily.

**Comment by dmakarov** [comment]
As a rule, we prefer not to diverge from rust-lang/rust more than we absolutely have to.  If you need to make changes to have rust built on your system, I suggest making a PR to rust-lang/rust and we will pick up the changes from upstream. In terms of the build system compatibility our fork is no different than upstream rust-lang/rust.  Like I said if rust-lang/rust builds on your system, solana-labs/rust should build too.

`build.sh` is a convenience wrapper around `x.py` which in turn is a wrapper around Rust bootstrap command, so I'm not sure it makes sense to add new capabilities to it. They should be added via modifications to the bootstrap command.

**Comment by drozdziak1** [comment]
Yeah, I think I'll pick nixing the BPF toolchain later, I managed to `patchelf` the binary distribution of `solana` and `bpf-tools`. Thanks for getting back to me
